<nav>
                <select id="menu" onchange="changePage()">
                    <option value="">
                        Please select
                    </option>
                    <option value="index.php">
                        Home
                    </option>
                    <option value="pets.php">
                        Pets
                    </option>
                    <option value="add.php">
                        Add
                    </option>
                    <option value="gallery.php">
                        Gallery
                    </option>
                </select>
            </nav>